---
- name: Install Wazuh Agent
  hosts: linux
  become: true
  become_method: sudo
  vars:
    wazuh_manager: 'waz-01.lab.sponar.de'

  tasks:
    - name: Import Wazuh GPG key (Debian)
      ansible.builtin.shell:
        cmd: curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --dearmor -o /usr/share/keyrings/wazuh.gpg
        creates: /usr/share/keyrings/wazuh.gpg
      when: ansible_os_family == "Debian"

    - name: Add Wazuh repository (Debian)
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main"
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Wazuh agent (Debian)
      ansible.builtin.apt:
        name: wazuh-agent
        state: present
        update_cache: yes
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}"
      when: ansible_os_family == "Debian"

    - name: Import Wazuh GPG key (RedHat)
      ansible.builtin.shell:
        cmd: rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Add Wazuh repository (RedHat)
      ansible.builtin.yum_repository:
        name: wazuh
        description: "EL-$releasever - Wazuh"
        baseurl: https://packages.wazuh.com/4.x/yum/
        gpgcheck: yes
        gpgkey: https://packages.wazuh.com/key/GPG-KEY-WAZUH
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Install Wazuh agent (RedHat)
      ansible.builtin.dnf:
        name: wazuh-agent
        state: present
      environment:
        WAZUH_MANAGER: "{{ wazuh_manager }}"
      when: ansible_os_family == "RedHat"

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Enable and start Wazuh agent service
      systemd:
        name: wazuh-agent
        state: started
        enabled: yes

- name: Install Wazuh Agent on Windows
  hosts: windows
  vars:
    wazuh_manager: 'waz-01.lab.sponar.de'
    wazuh_version: '{{ wazuh_version }}'

  tasks:
    - name: Download and install Wazuh agent
      win_shell: |
        Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-{{ wazuh_version }}.msi -OutFile $env:tmp\wazuh-agent
        msiexec.exe /i $env:tmp\wazuh-agent /q WAZUH_MANAGER='{{ wazuh_manager }}'
      args:
        creates: 'C:\Program Files (x86)\ossec-agent\wazuh-agent.exe'

    - name: Start Wazuh service
      win_service:
        name: Wazuh
        state: started
        start_mode: auto
