- hosts: linux
  become: true
  become_method: sudo
  vars:
    checkmk_host: "chk-01.lab.sponar.de"
    api_user: "automation"
    btw_monitoring_secret: "{{ lookup('bitwarden.secrets.lookup', '615b1a5f-719d-43eb-9c61-b31f008369f6', access_token='0.e49261c2-75c3-40c0-b961-b20d009f03e7.1eRaZ1zT800Th8ucN66uFsoz0khUkQ:8+ogReBqY3zxeG+lh54vfQ==') }}"
    api_secret: "{{ btw_monitoring_secret | string }}"
    site_id: "monitoring"
    downtime_start: "4 minutes"
    downtime_end: "15 minutes"
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Schedule CheckMK Downtime if Reboot is required
      uri:
        url: "https://{{ checkmk_host }}/{{ site_id }}/check_mk/api/1.0/domain-types/downtime/collections/host"
        method: POST
        force_basic_auth: true
        user: "{{ api_user }}"
        password: "{{ api_secret }}"
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
        body_format: json
        body:
          start_time: "{{ lookup('pipe', 'date -Is --date=\"{{ downtime_start }}\"') | trim }}"
          end_time: "{{ lookup('pipe', 'date -Is --date=\"{{ downtime_end }}\"') | trim }}"
          recur: "fixed"
          duration: 0
          comment: "Daily Downtime DUI"
          downtime_type: "host"
          host_name: "{{ inventory_hostname }}"
        status_code: 204
      delegate_to: lin-01.lab.sponar.de
      # when: reboot_required_file.stat.exists

    - name: Schedule reboot the box if kernel updated
      command: shutdown -r +5 "Reboot in 5 minutes for kernel updates"
      when: reboot_required_file.stat.exists
